Repository part4-team9/global-nomad, pull requests merged in 2024-08, with the labels that each got.

#31 Refactor: black버튼 hover색상 변경
  .github/workflows/preview.yml
  app/_components/button/index.tsx
Labels: feat

#30 Feat: 헤더 상태 관리
  app/(route)/(auth)/login/_components/log-in-form.tsx
  app/(route)/(auth)/signup/_components/sign-up-form.tsx
  app/(route)/my/index.tsx
  app/_actions/index.ts
  app/_apis/authentication/index.ts
  app/_apis/type/index.ts
  app/_apis/user/index.ts
  app/_components/example-axios/index.tsx
  app/_components/header/_component/guest-header.tsx
  app/_components/header/_component/header-dropdown.tsx
  app/_components/header/_component/logout.tsx
  app/_components/header/_component/user-header.tsx
  app/_components/header/index.tsx
  app/_hooks/use-is-login.ts
  app/_hooks/useBackgroundClick.ts
  app/_libs/authService.ts
  app/page.tsx
  app/store/useUserStore.ts
  package.json
  public/assets/images/default-profile.png
  yarn.lock
Labels: feat

#20 Feat: Rating 컴포넌트 제작
  app/_components/rating/index.tsx
  public/assets/icons/star.svg
Labels: feat

#40 Chore: 폰트 시스템 개편
  styles/tailwind.typography.ts
Labels: chore

#44 Feat: footer 컴포넌트 구현
  app/(route)/eunbin-test/page.tsx
  app/_components/common-layout/index.tsx
  app/_components/footer/index.tsx
  app/layout.tsx
  public/assets/icons/github.svg
  public/assets/icons/logo-white.svg
  public/assets/icons/notion.svg
  styles/globals.css
Labels: feat

#38 Feat: Card Frame 컴포넌트
  .eslintignore
  .eslintrc.js
  .gitattributes
  .prettierignore
  .prettierrc
  .prettierrc.js
  app/_components/card-frame/_components/card-contents-wrapper/index.tsx
  app/_components/card-frame/index.tsx
  app/_components/example-axios/index.tsx
  app/_components/example-zustand/index.tsx
  app/_hooks/useModal.ts
  app/_mocks/forCardFrame.ts
  app/_stores/index.ts
  app/_stores/useExampleStore.ts
  app/_types/card.ts
  app/_utils/format.ts
  eslint/tailwindcss.js
  next.config.mjs
  package.json
  postcss.config.mjs
  prettier/base.js
  prettier/tailwindcss.js
  styles/tailwind.screens.ts
  styles/tailwind.typography.ts
  yarn.lock
Labels: feat

#35 Feat: Main Page 제작
  app/(route)/main/_components/AllActivityLists/ActivityGrid/ActivityGrid.tsx
  app/(route)/main/_components/AllActivityLists/index.tsx
  app/(route)/main/_components/Banner/index.tsx
  app/(route)/main/_components/Button/index.tsx
  app/(route)/main/_components/CategoryLists/index.tsx
  app/(route)/main/_components/HotActivityLists/ActivityCard/ActivityCard.tsx
  app/(route)/main/_components/HotActivityLists/LoadingError/LoadingError.tsx
  app/(route)/main/_components/HotActivityLists/index.tsx
  app/(route)/main/_components/Pagination/index.tsx
  app/(route)/main/_components/SearchBox/index.tsx
  app/(route)/main/_components/SortLists/index.tsx
  app/(route)/main/page.tsx
  app/_components/example-axios/index.tsx
  app/_components/modal/index.tsx
  app/_components/rating/index.tsx
  app/_hooks/activities/useGetActivities.ts
  app/_hooks/activities/useInfinitiActivities.ts
  app/_hooks/activities/useIntersectionObserver.ts
  app/_hooks/activities/usePagination.ts
  app/_hooks/activities/useResFetchCount.ts
  app/_hooks/activities/useScrollable.ts
  app/_libs/activities/activitiesApi.ts
  app/_types/activities/types.ts
  app/layout.tsx
  app/page.tsx
  next.config.mjs
  public/assets/icons/arrow-right-disabled.svg
  public/assets/icons/arrow-right.svg
  public/assets/icons/bed.svg
  public/assets/icons/cost-btn.svg
  public/assets/icons/spinner.svg
  styles/globals.css
  styles/tailwind.backgroundImage.ts
  styles/tailwind.screens.ts
  tailwind.config.ts
Labels: feat

#33 Feat: 체험 등록, 수정 페이지 작업
  app/(route)/(auth)/login/_components/log-in-form.tsx
  app/(route)/(auth)/signup/_components/sign-up-form.tsx
  app/(route)/activity/edit/[id]/_components/ActivityEditForm/index.tsx
  app/(route)/activity/edit/[id]/_components/EditLayout/index.tsx
  app/(route)/activity/edit/[id]/page.tsx
  app/(route)/activity/register/_components/ActivityRegisterForm/index.tsx
  app/(route)/activity/register/_components/AddressModal/index.tsx
  app/(route)/activity/register/_components/BannerImage/index.tsx
  app/(route)/activity/register/_components/CalendarPicker/index.tsx
  app/(route)/activity/register/_components/CommonModal/index.tsx
  app/(route)/activity/register/_components/FileInput/index.tsx
  app/(route)/activity/register/_components/IntroduceImage/index.tsx
  app/(route)/activity/register/_components/PriceButtons/index.tsx
  app/(route)/activity/register/_components/RegisterLayout/index.tsx
  app/(route)/activity/register/_components/ScheduleEditor/index.tsx
  app/(route)/activity/register/_components/SchedulePicker/index.tsx
  app/(route)/activity/register/page.tsx
  app/_apis/activities/getActivity.ts
  app/_apis/activities/patchActivity.ts
  app/_apis/activities/postActivity.ts
  app/_apis/activities/postImage.ts
  app/_components/CommonLayout/index.tsx
  app/_components/Footer/index.tsx
  app/_components/Input/index.tsx
  app/_components/SelectBox/index.tsx
  app/_components/SelectBoxList/index.tsx
  app/_components/SideStickyLayout/index.tsx
  app/_components/Textarea/index.tsx
  app/_components/modal/index.tsx
  app/_components/select-box-list/index.tsx
  app/_components/select-box/index.tsx
  app/_components/textarea/index.tsx
  app/_constants/activity-category.ts
  app/_hooks/use-post-image.ts
  app/_hooks/useModalState.ts
  app/_hooks/useWindowSize.ts
  app/_libs/axios.ts
  app/_utils/formatNumber.ts
  app/_utils/generateTimeArray.ts
  app/layout.tsx
  app/page.tsx
  next.config.mjs
  package.json
  public/assets/icons/btn-minus.svg
  public/assets/icons/btn-plus-disabled.svg
  public/assets/icons/btn-plus.svg
  public/assets/icons/calendar.svg
  public/assets/icons/close.svg
  public/assets/icons/delete.svg
  public/assets/icons/next-month.svg
  public/assets/icons/plus.svg
  public/assets/icons/prev-month.svg
  styles/datepicker.css
  styles/globals.css
  styles/tailwind.screens.ts
  yarn.lock
Labels: feat

#52 [Feat] Write Review 컴포넌트 제작
  app/_components/write-review/index.tsx
  app/_components/write-review/review-card-frame/index.tsx
  app/_hooks/my-reservations/usePostReview.ts
  app/_libs/my-reservations/postReview.ts
  app/_utils/format.ts
  package.json
  public/assets/icons/x-btn.svg
  yarn.lock
Labels: feat

#56 Feat: 404 페이지 제작
  app/not-found.tsx
  public/assets/images/404-error.gif
Labels: feat

#53 Feat: 내 정보 수정 페이지 구현 완료
  app/(route)/activity/edit/[id]/_components/EditLayout/index.tsx
  app/(route)/activity/register/_components/RegisterLayout/index.tsx
  app/(route)/my/account/_components/AccountConfirm/index.tsx
  app/(route)/my/account/_components/AccountForm/index.tsx
  app/(route)/my/account/_components/CommonModal/index.tsx
  app/(route)/my/account/_components/EmailField/index.tsx
  app/(route)/my/account/_components/MyAccountClient/index.tsx
  app/(route)/my/account/_components/NewPasswordField/index.tsx
  app/(route)/my/account/_components/NicknameField/index.tsx
  app/(route)/my/account/_components/PasswordConfirmField/index.tsx
  app/(route)/my/account/page.tsx
  app/(route)/my/index.tsx
  app/(route)/my/page.tsx
  app/_actions/index.ts
  app/_apis/user/userAccount.ts
  app/_components/side-user-profile-card/index.tsx
  app/_hooks/use-post-image.ts
  app/_hooks/useModalState.ts
  app/_types/user.ts
  app/_types/userAccount.ts
  package.json
  public/assets/icons/default-profile.svg
  public/assets/lottie/loading.json
  yarn.lock
Labels: feat

#50 Feat: 예약 내역 페이지 작업
  app/(route)/(landing)/_components/CategoryCard/index.tsx
  app/(route)/(landing)/_components/CategorySection/index.tsx
  app/(route)/(landing)/_components/IntroduceService/index.tsx
  app/(route)/my/reservations/_components/CancelButton/index.tsx
  app/(route)/my/reservations/_components/CancelModal/index.tsx
  app/(route)/my/reservations/_components/CardDataTransformer/index.tsx
  app/(route)/my/reservations/_components/FilterDropdown/index.tsx
  app/(route)/my/reservations/_components/ReservationClient/index.tsx
  app/(route)/my/reservations/_components/ReservationContainer/index.tsx
  app/(route)/my/reservations/_components/ResultModal/index.tsx
  app/(route)/my/reservations/_components/ReviewButton/index.tsx
  app/(route)/my/reservations/_components/ReviewCardFrame/index.tsx
  app/(route)/my/reservations/_components/ReviewConfirmModal/index.tsx
  app/(route)/my/reservations/_components/ReviewModal/index.tsx
  app/(route)/my/reservations/page.tsx
  app/_apis/reservations/getReservations.ts
  app/_apis/reservations/patchCancelReservation.ts
  app/_components/NoReservation/index.tsx
  app/_components/card-frame/_components/card-contents-wrapper/index.tsx
  app/_components/card-frame/index.tsx
  app/_components/write-review/review-card-frame/index.tsx
  app/_constants/reservation-filter.ts
  app/_hooks/my-reservations/usePostReview.ts
  app/_hooks/useSelectBox.ts
  app/_mocks/forCardFrame.ts
  app/_types/card.ts
  app/_types/myReservations.ts
  app/layout.tsx
  public/assets/icons/check-black.svg
  public/assets/icons/cost-btn.svg
  public/assets/icons/empty.svg
  public/assets/lottie/check-black.json
  public/assets/lottie/empty-lottie.json
  public/assets/lottie/fail.json
  public/assets/lottie/success.json
  yarn.lock
Labels: feat

#57 Feat: 예약 현황 페이지 작업
  app/(route)/(auth)/layout.tsx
  app/(route)/(auth)/login/_components/LogInForm/index.tsx
  app/(route)/(auth)/login/page.tsx
  app/(route)/(auth)/signup/_components/SignUpForm/index.tsx
  app/(route)/(auth)/signup/page.tsx
  app/(route)/my/reservation-status/_component/CardApprove/index.tsx
  app/(route)/my/reservation-status/_component/CardPending/index.tsx
  app/(route)/my/reservation-status/_component/CardRejected/index.tsx
  app/(route)/my/reservation-status/_component/CardSection/index.tsx
  app/(route)/my/reservation-status/_component/NoReservation/index.tsx
  app/(route)/my/reservation-status/_component/RegisterStatusLayout/index.tsx
  app/(route)/my/reservation-status/_component/RegisterStatusModal/index.tsx
  app/(route)/my/reservation-status/page.tsx
  app/_actions/index.ts
  app/_apis/reservation/getMyActivities.ts
  app/_apis/user/index.ts
  app/_apis/user/userAccount.ts
  app/_components/calendar-notice/_components/calendar-cell/index.tsx
  app/_components/calendar-notice/_components/calendar-header/index.tsx
  app/_components/calendar-notice/index.tsx
  app/_components/header/_component/GuestHeader/index.tsx
  app/_components/header/_component/HeaderDropDown/index.tsx
  app/_components/header/_component/LogoutButton/index.tsx
  app/_components/header/_component/UserHeader/index.tsx
  app/_components/header/_component/header-dropdown.tsx
  app/_components/header/_component/user-header.tsx
  app/_components/header/index.tsx
  app/_components/side-user-profile-card/index.tsx
  app/_hooks/useAuthStatus.ts
  app/_hooks/useGetReservation.ts
  app/_libs/authService.ts
  app/_libs/axios.ts
  app/_mocks/notice-calendar-example-reservations.ts
  app/_stores/useUserStore.ts
  app/_types/authentication.ts
  app/_types/myActivities.ts
  app/_utils/isLogin.ts
  app/_utils/reservation.ts
  app/layout.tsx
  package.json
  yarn.lock
Labels: feat

#72 Fix: 내 정보 이메일 캐싱 문제, isLogin 훅 세션스토리지 key값 변경
  app/(route)/my/account/_components/AccountConfirm/index.tsx
  app/(route)/my/account/_components/EmailField/index.tsx
  app/_hooks/useAuthStatus.ts
Labels: fix

#74 Fix: 이미지 버그 수정
  app/(route)/my/account/_components/AccountConfirm/index.tsx
  app/_components/header/_component/UserHeader/index.tsx
Labels: fix

#58 Feat: 체험 상세 페이지 제작
  app/(route)/activity/details/[id]/page.tsx
  app/(route)/activity/details/_components/Calendar/MobileCalendar.tsx
  app/(route)/activity/details/_components/Calendar/MobilePeopleCounter.tsx
  app/(route)/activity/details/_components/Calendar/PCCalendar.tsx
  app/(route)/activity/details/_components/Calendar/PeopleCounter.tsx
  app/(route)/activity/details/_components/Calendar/ReservationSummary.tsx
  app/(route)/activity/details/_components/Calendar/TabletCalendar.tsx
  app/(route)/activity/details/_components/Calendar/TimeSelection.tsx
  app/(route)/activity/details/_components/Calendar/index.tsx
  app/(route)/activity/details/_components/Calendar/types.ts
  app/(route)/activity/details/_components/Dropdown/index.tsx
  app/(route)/activity/details/_components/ExperienceClientPage/index.tsx
  app/(route)/activity/details/_components/ExperienceDetail/ExperienceInfo.tsx
  app/(route)/activity/details/_components/ExperienceDetail/ImageSlider.tsx
  app/(route)/activity/details/_components/ExperienceDetail/Reviews.tsx
  app/(route)/activity/details/_components/ExperienceDetail/index.tsx
  app/(route)/activity/details/_components/ExperienceDetail/types.ts
  app/(route)/activity/details/_components/NaverMap/index.tsx
  app/_apis/activities/fetchExperienceData.ts
  app/_apis/activities/fetchReviewsData.ts
  app/_components/header/_component/UserHeader/index.tsx
  app/_hooks/useWindowSize.ts
  app/_libs/fetchCoordinates.ts
  app/_types/details/types.ts
  app/_types/naver-maps.d.ts
  app/api/getCoordinates/route.ts
  package.json
  public/assets/icons/Location.svg
  public/assets/icons/cal-arrow.svg
  public/assets/icons/cal-next.svg
  public/assets/icons/cal-prev.svg
  public/assets/icons/minus-button.svg
  public/assets/icons/move-left.svg
  public/assets/icons/move-right.svg
  public/assets/icons/option-menu.svg
  public/assets/icons/plus-button.svg
  yarn.lock
Labels: feat

#62 Feat: Carousel 제작
  .eslintrc.js
  app/(route)/main/_components/AllActivityLists/ActivityGrid/ActivityGrid.tsx
  app/(route)/main/_components/AllActivityLists/index.tsx
  app/(route)/main/_components/Banner/index.tsx
  app/(route)/main/_components/CategoryLists/index.tsx
  app/(route)/main/_components/HotActivityLists/ActivityCard/ActivityCard.tsx
  app/(route)/main/_components/HotActivityLists/HotListsCarousel/HotListsCarouselBtn/index.tsx
  app/(route)/main/_components/HotActivityLists/HotListsCarousel/index.tsx
  app/(route)/main/_components/HotActivityLists/LoadingError/LoadingError.tsx
  app/(route)/main/_components/HotActivityLists/index.tsx
  app/(route)/main/_components/SearchBox/index.tsx
  app/_components/Carousel/CarouselDotBtn/index.tsx
  app/_components/Carousel/index.tsx
  app/_hooks/activities/useCarousel.ts
  package.json
  public/assets/icons/carousel-btn.svg
  public/assets/icons/hot-activity-btn.svg
  styles/globals.css
  styles/tailwind.backgroundImage.ts
  yarn.lock
Labels: feat

#76 Fix: 이미지 로딩 버그 수정
  app/(route)/activity/(form)/_components/FileInput/index.tsx
  app/(route)/activity/(form)/_components/IntroduceImage/index.tsx
  app/(route)/activity/(form)/edit/[id]/_components/EditLayout/index.tsx
  app/_components/header/index.tsx
  styles/globals.css
Labels: fix

#77 Fix: Pagination 수정
  app/(route)/activity/details/_components/ExperienceDetail/Reviews.tsx
  app/(route)/activity/details/_components/ExperienceDetail/index.tsx
  app/(route)/main/_components/AllActivityLists/ActivityGrid/ActivityGrid.tsx
  app/(route)/main/_components/AllActivityLists/index.tsx
  app/(route)/main/_components/Button/index.tsx
  app/(route)/main/_components/HotActivityLists/HotListsCarousel/index.tsx
  app/(route)/main/_components/Pagination/index.tsx
  app/_components/Carousel/index.tsx
  app/_hooks/activities/usePagination.ts
Labels: fix

#70 Fix: fix side user profile card
  app/(route)/my/page.tsx
  app/_actions/index.ts
  app/_components/Carousel/index.tsx
  app/_components/FullScreenLoader/index.tsx
  app/_components/SideStickyLayout/index.tsx
  app/_components/SideUserProfileCard/_components/AvatarEditBtnWrapper/index.tsx
  app/_components/SideUserProfileCard/_components/ChangeProfileImageModal/index.tsx
  app/_components/SideUserProfileCard/_components/ProfileButton/index.tsx
  app/_components/SideUserProfileCard/index.tsx
  app/_components/header/_component/HeaderDropDown/index.tsx
  app/_components/side-user-profile-card/_components/avatar-edit-wrapper/index.tsx
  app/_components/side-user-profile-card/index.tsx
  app/_constants/sideUserProfileCard.ts
  app/_libs/userService.ts
  app/_stores/useUserInfoState.ts
  app/_utils/convertURLtoFile.ts
  app/components/ui/Spinner.tsx
  app/components/ui/skeleton.tsx
  components.json
  package.json
  public/assets/icons/loader-circle.svg
  public/assets/icons/profile-card/reservation-status.tsx
  styles/tailwind.animation.ts
  styles/tailwind.keyframes.ts
  tailwind.config.ts
  yarn.lock
Labels: feat

#83 Feat: Alarm List
  app/_components/header/_component/AlarmList/index.tsx
  app/_components/header/_component/UserHeader/index.tsx
  app/_libs/notificationService.ts
  app/_utils/notification.ts
  app/layout.tsx
  public/assets/icons/alarmList/alarm-dot-confirmed.svg
  public/assets/icons/alarmList/alarm-dot-declined.svg
  public/assets/icons/alarmList/alarm-dot-new.svg
  public/assets/icons/alarmList/alarm-dot.svg
  public/assets/icons/alarmList/message-dashed.svg
Labels: feat

#87 Feat: 내 체험 관리
  app/(route)/my/activities/page.tsx
  app/_components/SideUserProfileCard/index.tsx
  app/_components/card-frame/_components/card-contents-wrapper/index.tsx
  app/_libs/myActivitiesService.ts
  app/_types/activities/types.ts
  app/_types/card.ts
Labels: feat
